import assert from "node:assert/strict";
import { mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Broker } from "./broker.mjs";

const broker = await new Broker(join(await mkdtemp(join(tmpdir(), "a2a-")), "broker.json")).load();
const wf = await broker.createWorkflow({ title: "Image module", request: "Generate a 1440x1440 product image" });
assert.equal(wf.status, "needs_confirmation");
await broker.confirm(wf.id);
let next = await broker.next("task-decomposer");
assert.equal(next.task.stage, "decompose");
await broker.complete(wf.id, next.task.id, { status: "PASS", summary: "done", defects: [] });
next = await broker.next("architecture-agent");
assert.equal(next.task.stage, "architecture");
await broker.send({ workflowId: wf.id, from: "architecture-agent", to: "backend-agent", type: "DEFECT", taskId: next.task.id, payload: { owner: "backend-agent", title: "validation", reproduction: "missing" } });
const repair = Object.values(broker.snapshot().workflows[wf.id].tasks).find(t => t.stage === "repair");
assert.equal(repair.agent, "backend-agent");
const failed = await broker.createWorkflow({ title: "Failed task", request: "must not spin" });
await broker.confirm(failed.id);
const failedTask = await broker.next("task-decomposer");
await broker.complete(failed.id, failedTask.task.id, { status: "BLOCKED", summary: "must not retry automatically", defects: [] });
assert.equal(await broker.next("task-decomposer"), null);
console.log("broker workflow and direct defect routing pass");
